
# mybatis-plus
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.medcine.base.entity  # 注意：对应实体类的路径
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      table-underline: true
      #逻辑删除配置
      logic-not-delete-value: 0
      logic-delete-value: 1






